"""Change nema of column in Artist table

Revision ID: 038ca236a951
Revises: 15acd25c47cd
Create Date: 2022-11-19 15:37:13.799581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038ca236a951'
down_revision = '15acd25c47cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###
