"""change data type in genres columns to Array of Strings

Revision ID: ae9948118045
Revises: bc29c747be57
Create Date: 2022-11-19 17:09:50.826047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9948118045'
down_revision = 'bc29c747be57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
