"""change data type in genres columns to Array of Strings

Revision ID: ee9ce5acccfc
Revises: ae9948118045
Create Date: 2022-11-19 17:10:22.095187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9ce5acccfc'
down_revision = 'ae9948118045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('phone', sa.ARRAY(String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'phone')
    # ### end Alembic commands ###
